modLoader="javafml"
loaderVersion="[43,)"
license="CC0 1.0"
issueTrackerURL="https://github.com/ChiefArug/Cesium/issues"
[[mods]]
modId="cesium"
version="${file.jarVersion}"
displayName="Cesium"
logoFile="pack.png"
authors="ChiefArug"
displayTest="IGNORE_SERVER_VERSION"
description='''
Cesium is the latest in anti performance mods! Render all the chunks, even those hidden by blocks in front of you!

Intended for people playing with wacky shaders that warp the world allowing you to see what you otherwise wouldn't be able to
'''

[[dependencies.cesium]]
    modId="forge"
    mandatory=true
    versionRange="[43.3.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cesium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
